Us28 profil page
WildCodeSchool/lille-0919-js-projet3-lanur pull request #16
Opened 2020-01-13 16:10 UTC by Adwarf14

2020-01-14 09:07 UTC, LoicBrassart commented
Please stop asking for my reviews, the first one should always be the SM's :pray:

2020-01-14 12:24 UTC, Gumatan submitted a review, later dismissed

2020-01-14 13:49 UTC, LoicBrassart requested changes
`.env` on GH, I won't read the rest of this PR.

2020-01-14 14:00 UTC, GautierMille commented
> `.env` on GH, I won't read the rest of this PR.

.env deletd

2020-01-15 13:12 UTC, Gumatan submitted a review, later dismissed

2020-01-16 13:51 UTC, LoicBrassart requested changes
Please clean your code (nothing broken, just instructions I don't want to see on `dev` and things that *will* break when in production)

2020-01-16 13:51 UTC, LoicBrassart commented on frontend/src/components/EditProfile/Profile.jsx
> +    console.log(e.target.files);
Nope!

2020-01-16 13:51 UTC, LoicBrassart commented on frontend/src/components/EditProfile/Profile.jsx
> +    axios.post("http://localhost:5050/imgupload", data).then(response => {
Stop using `localhost`

2020-01-16 13:51 UTC, LoicBrassart commented on frontend/src/components/EditProfile/Profile.jsx
> +      alert("image added with success");
I think this `alert` really breaks UX, and I'd prefer a quiet notification (if you really *need* to inform your user)

2020-01-16 15:15 UTC, Gumatan approved these changes

2020-01-17 15:42 UTC, LoicBrassart approved these changes
SnE

2020-01-17 15:42 UTC, LoicBrassart commented on frontend/src/components/EditProfile/Profile.jsx
> +    "https://via.placeholder.com/250"
(Please stop adding placeholders !)

2020-01-17 15:48 UTC, merged