Us36 posts likes
WildCodeSchool/lille-0919-js-projet3-lanur pull request #36
Opened 2020-01-23 15:03 UTC by jervalles

2020-01-23 16:17 UTC, Gumatan submitted a review, later dismissed

2020-01-24 14:22 UTC, LoicBrassart requested changes
Nope.

2020-01-24 14:22 UTC, LoicBrassart commented on backend/index.js
> +    console.log(req.user);
Nope

2020-01-24 14:22 UTC, LoicBrassart commented on backend/index.js
> +            console.log(err);
Nope

2020-01-24 14:22 UTC, LoicBrassart commented on backend/index.js
> +            console.log(err);
Nope

2020-01-24 14:22 UTC, LoicBrassart commented on frontend/src/components/NewsFeed.jsx
> +        console.log(data);
nope

2020-01-24 14:27 UTC, Gumatan approved these changes

2020-01-24 15:25 UTC, LoicBrassart approved these changes
No More Evil

2020-01-24 15:28 UTC, merged