Us01 sign up form
WildCodeSchool/lille-0919-js-projet3-lanur pull request #4
Opened 2019-12-06 10:52 UTC by Gumatan

2019-12-06 13:15 UTC, Adwarf14 commented on frontend/src/components/SignIn.jsx
> +          <input type="text" />
type = "password"

2019-12-06 13:20 UTC, Adwarf14 submitted a review, later dismissed

2019-12-06 14:13 UTC, LoicBrassart requested changes
- No fonts outside the `public` folder

2019-12-06 14:13 UTC, LoicBrassart commented on frontend/src/components/style/variables.scss
> +$mainPurple: #8d20ae;
I'd advice against using color names in variable names : if your client wants to transition the main color to YellowGreen ( <3 ), you'll have something like `$mainPurple: yellowgreen`... ಠ_ಠ

2019-12-06 15:21 UTC, Adwarf14 approved these changes

2019-12-11 11:09 UTC, LoicBrassart approved these changes
SnE

2019-12-11 12:32 UTC, merged