Us22 post bdd
WildCodeSchool/lille-0919-js-projet3-lanur pull request #8
Opened 2019-12-16 09:32 UTC by jervalles

'Backend ready' with express routes
The Front Post from Fil d'actu page will arrive when the actuals PR will merge

2019-12-16 13:39 UTC, Gumatan submitted a review, later dismissed

2019-12-16 17:00 UTC, LoicBrassart requested changes
Some minor changes to do

2019-12-16 17:00 UTC, LoicBrassart commented on backend/index.js
> +  res.header("Access-Control-Allow-Origin", "http://localhost:3001"); // update to match the domain you will make the request from
Very bad idea: you'll forget to update this value
Instead, use the `cors` package to get rid of this topic in one move :ok_hand:

2019-12-16 17:00 UTC, LoicBrassart commented on backend/index.js
> +app.get("/", (req, res, next) => {
Useless route, to delete

2019-12-16 17:00 UTC, LoicBrassart commented on backend/index.js
> +app.post("/api/users", (req, res) => {
Beware: this route will be deleted soon once you have nailed the authentication with Passport!

2019-12-16 17:00 UTC, LoicBrassart commented on backend/index.js
> +  db.query("SELECT * from post", (err, results) => {
Do not "SELECT *" me, young man! è_é

2019-12-17 08:34 UTC, Gumatan approved these changes

2019-12-17 08:49 UTC, LoicBrassart approved these changes
SnE ;-)

2019-12-17 08:50 UTC, merged